### PR TITLE
Release 1.0.4

### PR DESCRIPTION
**Pull request by Progi1984**

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Comment by sarahdib** [comment]
When i click on traduct the back office
Capture d’écran 2020-06-01 à 14 28 20

**Comment by Progi1984** [comment]
@sarahdib Could you send me a video for this bug (it seems idem as #4 and I don't reproduce it) ?

**Comment by Progi1984** [comment]
@sarahdib Bug confirmed : #4

**Comment by Progi1984** [comment]
Ping @sarahdib

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @sarahdib

**Pull request merged**
